# Make sure to rename this file to config.toml in order for it to work!

[login]
    # your bot's username
    username = "myawesomebot"
    # your bot's access token
    token = "1n2b192nb891n2b9n1v912v9n"

[general]
    # the prefix for commands
    prefix = "!"
    # the Twitch channels to join
    # to avoid issues, prefix every channel with a #
    channels = ["#myawesomechannel"]
    # whether to reconnect to Twitch when disconnected
    auto_reconnect = true
    # whether the bot should chat in colored messages with /me
    colored = true

[logging]
    # whether to log chat messages
    messages = true
    # whether to log command usage
    commands = true

[imgur]
    # the Imgur album ID to upload images to
    album_id = "aADK31l"
    # the Imgur client ID to use
    client_id = "0fn120n8gn0a9s"
    # the Imgur client secret to use
    client_secret = "pen897b9678nvna7onv8a4van4w8w7698763"

[commands.exec]
    # the users that can use the exec command
    whitelist = ["awesomeuser"]

[commands.imgur]
    # the users that can use the imgur command
    whitelist = ["awesomeuser"]
    # if you want to explicetely disable a command, you can do it like this:
    # enabled = false

[commands.join]
    # the users that can use the join command
    whitelist = ["awesomeuser"]

[commands.leave]
    # the users that can use the leave command
    whitelist = ["awesomeuser"]

[commands.peter]
    # the users that can use the peter command
    whitelist = ["awesomeuser"]

[commands.reload]
    # the users that can use the reload command
    whitelist = ["awesomeuser"]

[commands.restart]
    # the users that can use the restart command
    whitelist = ["awesomeuser"]

[commands.stop]
    # the users that can use the stop command
    whitelist = ["damnrelentless"]

[commands.whitelist]
    whitelist = ["damnrelentless"]

# Do not edit anything below!
# This is used to store some persistent data for the bot and it's automated.
[persistent]
    restartOrigin = ""
    peter = false
