name: CI

on: [push, pull_request]

env:
  MOD_NAME: RLNTBot
  RELEASE_FILES: config LICENSE

jobs:
  check:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier Format
        run: npx pretty-quick --check --verbose

      - name: Lint with ESLint
        run: npm run lint

      - name: Build
        run: npm run build

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: check
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Setup envar
        run: echo RELEASE_NAME="$MOD_NAME-${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '14'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build the executables
        run: npm run build

      - name: Package Linux Redistributables
        run: zip -r $RELEASE_NAME-linux.zip $RELEASE_FILES dist/RLNTBot-linux

      - name: Package MacOS Redistributables
        run: zip -r $RELEASE_NAME-mac.zip $RELEASE_FILES dist/RLNTBot-macos

      - name: Package Windows Redisistributables
        run: zip -r $RELEASE_NAME-windows.zip $RELEASE_FILES dist/RLNTBot-win.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.RELEASE_NAME }}-linux.zip
            ${{ env.RELEASE_NAME }}-mac.zip
            ${{ env.RELEASE_NAME }}-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
